### ISSUE TITLE
Mapbox  pop up description does not work on mobile browsers

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#18]
Clicking on the dot does not display description and logs this error to console :
Unable to preventDefault inside passive event listener invocation.

**Comment by dalenewman** [comment]
I think it's this issue is https://github.com/mapbox/mapbox-gl-draw/issues/1019.  

A work-around is to give you the option to turn off the ability to draw in map options.  Most of the the time you're not drawing lines around dots on your mobile device so we can just turn that feature off on the maps that your mobile users use and the popups should work again.  I will see what I can do.

**Comment by dalenewman** [comment]
This change allows map popups to work on mobile chrome, as long as you don't add bulk actions.
