### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#2]
timezone transform doesn’t run on Linux

**Comment by dalenewman** [comment]
I haven't been had time to implement `TimeZoneTransform` which can convert from any timezone to another, but I did add `ToLocalTimeTransform` which converts from UTC to Orchard's configured time.

You'd use it like this:

```xml
<!-- Created is a date coming from the database stored as UTC -->
<add name="Created" type="datetime" t="toLocalTime()" />
```

**Comment by vlad2kgithub** [comment]
Thanks.

**Comment by vlad2kgithub** [comment]
toLocalTime() is not working

**Comment by dalenewman** [comment]
It was converting to the system's time zone, not time zone configured in Orchard.

**Comment by dalenewman** [comment]
`timezone(fromTimeZone,toTimeZone)` should work now, but using IANA time zones not Windows (see [this](https://techsupport.osisoft.com/Documentation/PI-Web-API/help/topics/timezones/iana.html)).  I checked it and it's working for me (Windows and Linux).  I'll re-open until I hear from you though.  Remember, use time zones like *America/Detroit* instead of *Eastern Standard Time*.
